In [ ]:
#designing own neural network without library

In [17]:
import numpy as np

In [18]:
#And operation
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T#different dimension of X and Y so taking transpose
print(Y)

[[0]
 [0]
 [0]
 [1]]


In [19]:
def sig(z):
    return 1/(1+np.exp(-z))

In [20]:
#no hidden layer
#multiplied with 2 and 1 is subtracted to get values between -1 and 1
weights=2*np.random.random((2,1))-1 #two inputs to one ouput node
bias=2*np.random.random(1)-1 #one bias to one output node
lr=0.1

In [21]:
#ranndom weights and bias generated and output calculated .. they are not optimized
output0=X
output=sig(np.dot(output0,weights)+bias)
output

array([[0.32583238],
       [0.29521389],
       [0.43712727],
       [0.40229115]])

In [ ]:
#for miltiple hidden layer
#weights of hidden layer
wh=2*np.random.random((2,2))-1 #two inputs to two hidden node in hidden layer
bh=2*np.random.random((1,2))-1 #one bias to two hidden node in hidden layer
#weights and bias of output layer
wo=2*np.random.random((2,1))-1#two inputs to one ouput node
bo=2*np.random.random((1,1))-1#one bias to one output node

In [ ]:
output0=X
outputh=sig(np.dot(output0,wh)+bh)
output=sig(np.dot(outputh,wo)+bo)
output


In [22]:
#now we will backpropagate find error and optimize the weights and bias values
#derivative of sig function will be used in error calculation
def derivative_sig(z):
    return sig(z)*(1-sig(z))

In [23]:
#for no hidden layer

for iter in range(10000):
    output0=X;
    output=sig(np.dot(output0,weights)+bias)
    
    first_term=output-Y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivative_sig(input_for_last_layer)
    first_two=first_term*second_term
    changes=np.array([[0.0],[0.0]])
    
    for i in range(2):#for 2 features
        for j in range(4):# for inputs
            changes[i][0] +=first_two[j][0]*output0[j][i]
    weights=weights-lr*changes
    bias_change=0.0
    for j in range(4):
    
        bias_change+=first_two[j][0] * 1
    bias=bias-lr*bias_change

output=sig(np.dot(X,weights)+bias)
print(output.shape)

weights,bias,output

        

(4, 1)


(array([[5.48138198],
        [5.48138196]]), array([-8.31475638]), array([[2.44816592e-04],
        [5.55471046e-02],
        [5.55471053e-02],
        [9.33888081e-01]]))

In [24]:
#optimize code using vector operation instead of for loop for changes and bias_change
lr=0.1
for iter in range(10000):
    first_term=output-Y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivative_sig(input_for_last_layer)
    first_two=first_term*second_term
    first_two.shape
   
    changes=np.dot(output0.T,first_two)
    weights=weights-lr*changes
    
    bias_change=np.sum(first_two)
    bias=bias-lr*bias_change
output=sig(np.dot(X,weights)+bias)

weights,bias,output

(array([[6.42088932],
        [6.42088933]]), array([-9.71957477]), array([[6.00919385e-05],
        [3.56163142e-02],
        [3.56163138e-02],
        [9.57799399e-01]]))